version: 2.1

defaults:
  default_image: &default_image
    docker:
      - image: cimg/aws:2024.03

jobs:
  build_and_deploy:
    <<: *default_image

    steps:
      - checkout

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install pnpm package manager
          command: |
            corepack enable --install-directory=/home/circleci/bin
            corepack prepare pnpm@latest-8 --activate
            pnpm config set store-dir .pnpm-store

      - run:
          name: Install Dependencies
          command: |
            pnpm install

      - run:
          name: Deploy using SST
          command: |
            pnpm sst deploy --stage=<< pipeline.git.branch >>

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

workflows:
  version: 2
  deploy:
    jobs:
      - build_and_deploy:
          context: sst